### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by FS22fanCatholic** [GMNGjoy/FS22_VariablePickupWidth#3]
This is just a suggestion but for this mod would it be possible to add a 50 meter working width option or even a 100 meter width option for all of the implement and maybe which could be after the virtual windrower and call it unreal windrower. Again this is just an idea, if it could be possible as I am no modder and you all do a wonderful job.

**Comment by GMNGjoy** [comment]
Interesting suggestion; I could potentially make an alternate version that
would do that - but in my opinion - 20m is already on the border of "too
far into the unreal side"... 50m is way over that "line" and is not
something that I'd be comfortable putting my name on. My goal and / or the
"feature" of this mod is two parts - the fact that you can change the
pickup width on the fly, and that it's a Cross-platform mod. Giants
tends to frown on unrealistic mods for all platforms, so I won't be trying
to "go bigger", especially for FS22.

That said, I plan to migrate this to FS25 and release the same mod as soon
as possible, but I don't want to give Giants ammunition to block it from
being released right away.

As an aside, I do agree that there are instances where you may want to go
bigger if you're on PC (maybe for a 16x map) - if you really want a 50m
version and you are on PC - contact me on discord, and I'll make it happen.

**Comment by FS22fanCatholic** [comment]
how can I contact you on discord as I don't know your discord name?

**Comment by GMNGjoy** [comment]
**Done.** You're welcome. 

https://github.com/GMNGjoy/FS22_VariablePickupWidth/releases/tag/1.50.0.0
